services:
  dwh:
    container_name: dwh
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - dwh_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-p", "${POSTGRES_PORT}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - fswe-demo

networks:
  fswe-demo:
    driver: bridge

volumes:
  dwh_data:
